repo_mining/ken-harvey_CollectFiles.py
repo_mining/ken_authorsFileTouches.py
repo_mining/ken_scatterplot.py

Uploading my versions of CollectFiles, authorsFileTouches, and scatterplot.

Mine repository

---

test_coverage_lab/.gitignore
test_coverage_lab/tests/test_account.py

My test case sets a password and verifies that the password is successfully stored as a hashed value.
Lines of code covered in models/account.py: 67, 71

Add test password hashing (Test Case #8)

---

test_coverage_lab/tests/test_account.py

Summary: Added test that creates an account with an empty email, and calls validate_email() on that account. The call is expected to raise an error.
Lines of code covered: 126 - 140

added test for invalid email input

---

test_coverage_lab/tests/test_account.py

Code creates a test account, commits it to the db, verifies its existence. It then deletes the account and reverifies its non-existence. 
Tests the function on lines 79-82 in models/account.py

Added a test for account deletion

---

.gitignore
tdd_lab/.gitignore

Pushing asap to avoid problems.

TDD gitignores. Group-4/.gitignore rules added. TDD/.gitignore added as given.

---

test_coverage_lab/tests/test_account.py

Ensures that creating an Account() without required fields raises an error. Validate that missing fields trigger the correct exception. 
Lines of code covered in models/account.py: 16-27 (Account class)
Lines of code in tests/test_account.py: 152-173

Added student 3 test case: test missing required fields

---

tdd_lab/src/counter.py
tdd_lab/tests/test_counter.py

@app.route('/counters/<name>', methods=['PUT'])
def increment_counter(name):
"""Increment the counter by 1."""
if not counter_exists(name):
return jsonify({"error": f"Counter {name} does not exist"}), status.HTTP_404_NOT_FOUND
COUNTERS[name] += 1
return jsonify({name: COUNTERS[name]}), status.HTTP_200_OK
•	Checks if the counter exists.
•	If the counter exists, it increments its value by 1 and returns the updated count.
•	If the counter does not exist, it returns a 404 Not Found error.
def test_increment_counter(self, client):
"""It should increment an existing counter using PUT /counters/<name>."""
create_response = client.post('/counters/incrementTest')
assert create_response.status_code == status.HTTP_201_CREATED
put_response = client.put('/counters/incrementTest')
assert …

Implement PUT /counters/<name> for incrementing counter (Student 5)

---

tdd_lab/src/counter.py
tdd_lab/tests/test_counter.py

Added test to handle invalid http methods. (lines 59-69 test_counter.py, lines 38-44 counter.py)

Add tdd test11 handle invalid http methods

---

tdd_lab/src/counter.py
tdd_lab/tests/test_counter.py

Student 7 Tasks:
Added a delete a counter failing test case inside test_counter.py
this function does:
-creats a counter
-Deletes the created counter
-check weather it has been deleted or not
Added end point for delete a coutner inside counter.py
this function does:
-checks if the coutner exists
-deletes said counter
-returns OK status after deleting

Added Delete a counter test case (student 7)

---

test_coverage_lab/tests/test_account.py

This PR adds tests for the deactivate() and reactivate() methods, covering lines 87 and 91 in account.py.
test_account_deactivate() makes sure that a functional account can be properly deactivated, and vice versa with test_account_reactivate().

Student 9: Add setup_disabled_account, add deactivate/reactivate tests

---

tdd_lab/src/counter.py
tdd_lab/tests/test_counter.py

Added Student 3's test case for TDD lab: Retrieve an existing counter
Test passes and successfully ensures that an existing counter can be retrieved

Added retrieve an existing counter test (student 3)

---

tdd_lab/src/counter.py
tdd_lab/tests/test_counter.py

Fixed indentation problem

---

.github/workflows/ci.yml

Per the ci_lab, step 1, part 3(d). Added the basic .yml github actions workflow file. Wait to merge until CI tests run. When the CI tests are ran successfully, a green checkmark will be shown at the Actions tab > CI Workflow.

Added initial GitHub Actions Workflow [Ken Harvey]

---

ci_lab/tests/test_counter.py

Added missing assertion for `Student #2` - `test_top_n_counters()` 
The function creates 3 counters "a", "b", and "reset" with final values of "a=1", "b=2", and "reset=0".
Then a GET call is made to retrieve the top 2 highest counters. 
The assertion I added checks if the response of that GET call is the top 2 highest counters (b=2 and a=1).

Added missing assertion for [Student #2] test case - Hardy Fenam

---

ci_lab/tests/test_counter.py

Added two lines that
-Safely extracts the 'error' filed from the json response
-checks for case-insensitivity

Added missing assertion for [Student 7] test case

---

ci_lab/tests/test_counter.py

Added missing assertion for student 3's test case to ensure 'a' or 'b' is in the response

Added missing assertion for Student 3 test case

---

ci_lab/tests/test_counter.py

Added missing assertion for student 8 test case

Add test assertion for student 8 test case

---

ci_lab/tests/test_counter.py

The pytest (#10) checks that the correct values are returned when asking for the values less-than a set limit.

Added assertion for test#10

---

gen_ai/task2.1/John_Zaleschuk_refactor_code.py
gen_ai/task2.2/John_Zaleschuk_docstring_update.py

I noticed that the outputting for loop at the bottom of the code for Task 2.1 could use some documentation. I gave ChatGPT the code and asked it to add clear documentation so that my future team members didn’t have to spend time figuring out what was happening in the output. 
Closes GenAI (Task 2.2) Issue #79  which was created for this task.
[https://chatgpt.com/share/67ba6430-bdec-800a-a12a-5782d4dcbbf8](url)

Completion of GenAi Lab (Task 2.2)

---

gen_ai/task2.1/John_Zaleschuk_refactor_code.py
gen_ai/task2.2/John_Zaleschuk_docstring_update.py
gen_ai/task2.3/John_Zaleschuk_code_simplification.py

My original prompt for the numpy library to be used during Task2.1 left my python script a convoluted mess. In this step, I ask chat GPT to simplify my complicated code. 
Closes GenAI (Task 2.3) Issue #81  which was created for this task.
[https://chatgpt.com/share/67ba699a-3b88-800a-a1a3-354672d23965](url)

Completion of GenAI Lab (Task 2.3)

---

gen_ai/task2.1/kevin_refactor_code.py

Refactored the stroke prediction model for better readability, efficiency, and maintainability.
- Re-evaluated logical functions
- Improved classification reporting and ROC curve plotting.
- Optimized hyperparameter tuning with GridSearchCV.
Suggested by ChatGPT https://chatgpt.com/share/67bede38-b050-8004-a9d8-d7e3a47e066a.
Closes issue #83

Refactored stroke prediction model using ChatGPT’s recommendation (GENAI Lab Task 2.1)

---

gen_ai/task2.2/kevin_docstring_update.py

Enhanced function documentation.
- Added docstrings explaining function inputs, outputs, and purpose.
- Improved readability
Suggested by ChatGPT https://chatgpt.com/share/67c11553-6294-8004-82e7-b3e59e8253da.
Closes #90

Improved documentation for old assignment using ChatGPT’s recommendation

---

gen_ai/task2.3/kevin_complex_code.py

Improved the Plaid API integration from complexity.
- Made `client_user_id` dynamic.
- Added clear function docstrings.
Suggested by ChatGPT https://chatgpt.com/share/67c126ed-33c8-8004-9f99-59440470a464.
Closes #92

Task 2.3 Understanding Complex Code on Plaid API

---

gen_ai/task2.1/kenharvey_refactor_code.java
gen_ai/task2.2/kenharvey_docstring_update.java
gen_ai/task2.3/kenharvey_understanding_code.java

These commits are for Tasks 1,2,3 on gen-ai lab.

Gen ai demonstration (Ken Harvey)
